version: "2"
services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "secret" # TODO: Change this
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  sgapi:
    container_name: sgapi
    restart: always
    image: ualmtorres/phalcon-apache-ubuntu
    ports:
      - "80:80"
    volumes:
      - ./api:/var/www/html
  sgapp:
    container_name: sgapp
    restart: always
    image: ualmtorres/phalcon-apache-ubuntu
    ports:
      - "81:80"
    volumes:
      - ./app:/var/www/html
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
